[preferred]
# Master Fallback: Check wlroots first for screen/windows, then fall back to GTK
default=wlr;gtk

# Granular Application Overrides
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Access=gtk
org.freedesktop.impl.portal.Notification=gtk
org.freedesktop.impl.portal.Secret=keepassxc