# home.nix matrix
xdg.configFile."fuzzel/fuzzel.ini".text = ''
    [main]
    font=JetBrainsMono Nerd Font:size=18
    fields=name,generic,exec
    terminal=ghostty
    prompt="❯ "
    icon-theme=Papirus-Dark
    width=30
    lines=18
    horizontal-pad=20
    vertical-pad=18
    inner-pad=10
    tabs=5

    [colors]
    background=#282828ff
    text=#ebdbb2ff
    selection=#504945ff
    selection-text=#ebdbb2ff
    border=#504945ff
    prompt=#fabd2fff
    input=#ebdbb2ff
    placeholder=#928374ff

    [border]
    width=2
    radius=10
'';
