# home.nix matrix
xdg.configFile."fuzzel/fuzzel.ini".text = ''
    [main]
    font=JetBrainsMono Nerd Font:size=11
    fields=name,generic,exec
    terminal=ghostty
    prompt="❯ "
    icon-theme=Papirus-Dark
    width=35
    horizontal-pad=20
    vertical-pad=15
    inner-pad=10

    [colors]
    background=1a1b26dd
    text=c0caf5ff
    match=ff9e64ff
    selection=33467cff
    selection-text=c0caf5ff
    border=7aa2f7ff

    [border]
    width=2
    radius=10
'';
