# ~/.config/hypr/hyprlauncher.conf

[general]
cache = true

[finders]
default_finder = desktop
unicode_prefix = .
math_prefix = =

[ui]
desktop_icons = true
desktop_launch_prefix = setpriv --reset-env --
